In [28]:
import numpy as np
my_list = [1,2,3,4]
arr1 = np.array( my_list )

arr1, my_list

(array([1, 2, 3, 4]), [1, 2, 3, 4])

In [3]:
arr1 * 10 # element wise

array([10, 20, 30, 40])

In [6]:
my_list * 10

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [8]:
my_list2 = [
    [1,2,3],
    [4,5,6]
]
my_list2[1]

[4, 5, 6]

In [10]:
arr2 = np.array( my_list2 )
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2[ : , 1] #  [행번호, 열번호]  : 은 전체

array([2, 5])

In [15]:
arr2[ :, [0,2]] # 팬시인덱싱(띄엄띄엄 추출 평가 자주나와!)

array([[1, 3],
       [4, 6]])

In [20]:
# 3차원 배열
arr3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)

np.arange(0,3,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9])

In [22]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [24]:
np.ones((2,2)) # 1로 채운 배열 2행 2열

array([[1., 1.],
       [1., 1.]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.full((2,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1]])

In [31]:
np.eye(5) #대각선으로 채운

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr1.ndim, arr2.ndim, arr3.ndim # 차원 형식

(1, 2, 3)

In [37]:
arr1.shape

(4,)

In [39]:
type( (3,) )

tuple

In [42]:
np.array([1.0,2,"3"])

array(['1.0', '2', '3'], dtype='<U32')

In [43]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [44]:
arr2, arr2.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [48]:
array = np.arange(16)
array.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [49]:
array.reshape

<function ndarray.reshape>

In [51]:
arr2.astype( np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [52]:
arr2.dtype

dtype('int32')

In [21]:
# 아파트 실거래데이터 읽기
import pandas as pd
apt_price = pd.read_csv(
    "./apt_price_2022.csv", 
    encoding = "cp949",
    skiprows=15,
    thousands=","
    
)
apt_price

시군구      번지     본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202109   
1      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202112   
2      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
3      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
4      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
...              ...     ...    ...   ...             ...      ...     ...   
16942  서울특별시 중랑구 중화동     450  450.0   0.0  한신아파트(103~109)    59.76  202207   
16943  서울특별시 중랑구 중화동     450  450.0   0.0  한신아파트(103~109)    84.03  202207   
16944  서울특별시 중랑구 중화동  274-51  274.0  51.0         한영(101)    84.69  202111   
16945  서울특별시 중랑구 중화동  274-51  274.0  51.0         한영(101)    84.69  202204   
16946  서울특별시 중랑구 중화동    11-7   11.0   7.0     현대휴앤미(102동)    76.43  202204   

       계약일  거래금액(만원)   층    건축년도          도로명  해제사유발생일  거래유형          중개사소재지  
0        2    220000   2  1987.0        언주로 3      NaN     -               -  
1        4    215000   3  1987.0        언주로 3      NaN  중개거래          서울 강남구  
2       12    220000   4  1987.0        언주로 3      NaN  중개거래          서울 강남구  
3       21    220000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
4       27    216000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
...    ...       ...  ..     ...          ...      ...   ...             ...  
16942   20     74000   3  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16943   27     91500  12  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16944    4     50000   2  2003.0   동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  
16945    9     49900   7  2003.0   동일로144길 74      NaN  중개거래          서울 중랑구  
16946   23     53000   6  2007.0  봉화산로27가길 19      NaN  중개거래          서울 중랑구  

[16947 rows x 15 columns]

In [22]:
apt_price.shape, apt_price.size

((16947, 15), 254205)

In [23]:
apt_price.values

array([['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '-', '-'],
       ['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '중개거래', '서울 강남구'],
       ['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '중개거래', '서울 강남구'],
       ...,
       ['서울특별시 중랑구 중화동', '274-51', 274.0, ..., nan, '중개거래',
        '서울 송파구, 서울 중랑구'],
       ['서울특별시 중랑구 중화동', '274-51', 274.0, ..., nan, '중개거래', '서울 중랑구'],
       ['서울특별시 중랑구 중화동', '11-7', 11.0, ..., nan, '중개거래', '서울 중랑구']],
      dtype=object)

In [24]:
평 = apt_price["전용면적(㎡)"] /3.03
평

0        26.392739
1        26.392739
2        26.392739
3        26.392739
4        26.392739
           ...    
16942    19.722772
16943    27.732673
16944    27.950495
16945    27.950495
16946    25.224422
Name: 전용면적(㎡), Length: 16947, dtype: float64

In [25]:
apt_price["거래금액(만원)"] / 평

0        8335.625860
1        8146.179817
2        8335.625860
3        8335.625860
4        8184.069026
            ...     
16942    3752.008032
16943    3299.357372
16944    1788.877081
16945    1785.299327
16946    2101.138296
Length: 16947, dtype: float64

In [26]:
%whos

Variable    Type         Data/Info
----------------------------------
apt_price   DataFrame                     시군구     <...>[16947 rows x 15 columns]
pd          module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
평           Series       0        26.392739\n1    <...>th: 16947, dtype: float64


In [30]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr5[1][1]
arr5[1,1]


4

In [34]:
arr6 = np.arange(9)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr6[1]

1

In [37]:
bidx = arr5 % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [39]:
arr5[bidx] # Ture에 위치하는 값을 추출, 1차원 반환 # 필수 출제

array([0, 2, 4, 6, 8])

In [40]:
arr5[arr5 % 2 == 0]

array([0, 2, 4, 6, 8])

In [43]:
apt_price[apt_price["층"] == 2]

0         True
1        False
2        False
3         True
4         True
         ...  
16942    False
16943    False
16944     True
16945    False
16946    False
Name: 층, Length: 16947, dtype: bool

In [48]:
# 서울특별식 강동구 암사동 거래정보만 추출
bidx = apt_price["시군구"] == "서울특별시 강동구 암사동"
sum(bidx) # True ->1 False -> 0

78

In [50]:
apt_price[ bidx ] # True

시군구     번지     본번   부번           단지명   전용면적(㎡)    계약년월  계약일  \
1625  서울특별시 강동구 암사동  466-3  466.0  3.0         내일쎄닛빌  111.4000  202205   11   
1626  서울특별시 강동구 암사동    461  461.0  0.0            대원   59.9000  202201   17   
1627  서울특별시 강동구 암사동  501-4  501.0  4.0         동양넥스빌   84.6800  202205   10   
1628  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109    8   
1629  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109   11   
...             ...    ...    ...  ...           ...       ...     ...  ...   
1698  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운   84.9800  202204   20   
1699  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운  114.0700  202205   30   
1700  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9979  202203   29   
1701  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9921  202204    1   
1702  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9628  202205    6   

      거래금액(만원)   층    건축년도         도로명  해제사유발생일  거래유형          중개사소재지  
1625     72000   9  2007.0  고덕로20나길 49      NaN   직거래               -  
1626     72500  12  1998.0      고덕로 52      NaN  중개거래  서울 강남구, 서울 강동구  
1627     80000  10  1999.0      상암로 41      NaN  중개거래          서울 강동구  
1628    129700  18  2008.0     고덕로 131      NaN     -               -  
1629    125500   3  2008.0     고덕로 131      NaN     -               -  
...        ...  ..     ...         ...      ...   ...             ...  
1698    137500  18  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1699    155000  11  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1700    130000   4  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1701    164000  23  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1702    152000   7  2019.0  올림픽로91길 30      NaN  중개거래        경기 성남분당구  

[78 rows x 15 columns]

In [51]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr5[ 0,2 ], arr5[1,1]

(2, 4)

In [53]:
#팬시 인덱싱
arr5[ [ 0,1], [2,1] ]

array([2, 4])

In [54]:
arr5[0, :]

array([0, 1, 2])

In [55]:
arr5[:, 0]

array([0, 3, 6])

In [61]:
arr5[:2, 1:]

array([[1, 2],
       [4, 5]])

In [62]:
arr5[-1:, 1:3]

array([[7, 8]])

In [64]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
b = arr5[:, 1]
b

array([1, 4, 7])

In [67]:
b[0] = 10
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [69]:
b = arr5[:,1].copy() #복사본
b

array([10,  4,  7])

In [71]:
b[0] = 1
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [73]:
# 중요 np.where
np.where(arr5 % 2 == 0)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 0, 2], dtype=int64))

In [74]:
np.where(arr5 % 2 == 0, "짝수", "홀수")

array([['짝수', '짝수', '짝수'],
       ['홀수', '짝수', '홀수'],
       ['짝수', '홀수', '짝수']], dtype='<U2')

In [76]:
# 조건에 맞는 항목은 "짝수", 아니면 원래값으로 유지
np.where(arr5 % 2 == 0, "짝수", arr5)

array([['짝수', '짝수', '짝수'],
       ['3', '짝수', '5'],
       ['짝수', '7', '짝수']], dtype='<U11')

In [79]:
# 중요 axis(축)
arr5.sum()

45

In [81]:
arr5.sum(axis = 0)

array([ 9, 21, 15])

In [82]:
arr5.sum(axis = 1)

array([12, 12, 21])